#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

// Tap Dance declarations
enum {
    TD_SHIFT_LAYER,
};

// Tap Dance state
typedef struct {
    bool is_press_action;
    int state;
} tap;

enum {
    SINGLE_TAP = 1,
    SINGLE_HOLD,
    DOUBLE_TAP,
    DOUBLE_HOLD,
    DOUBLE_SINGLE_TAP,
};

// Determine the current tap dance state
int cur_dance(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (!state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (!state->pressed) return DOUBLE_TAP;
        else return DOUBLE_HOLD;
    } else return 8; // Magic number for more than double tap
}

// Initialize tap structure associated with tap dance key
static tap td_state = {
    .is_press_action = true,
    .state = 0
};

// Tap dance functions
void td_shift_layer_finished(tap_dance_state_t *state, void *user_data) {
    td_state.state = cur_dance(state);
    switch (td_state.state) {
        case SINGLE_HOLD:
            register_code(KC_LSFT);
            break;
        case DOUBLE_HOLD:
            layer_on(2);
            break;
    }
}

void td_shift_layer_reset(tap_dance_state_t *state, void *user_data) {
    switch (td_state.state) {
        case SINGLE_HOLD:
            unregister_code(KC_LSFT);
            break;
        case DOUBLE_HOLD:
            layer_off(2);
            break;
    }
    td_state.state = 0;
}

// Tap Dance definitions
tap_dance_action_t tap_dance_actions[] = {
    [TD_SHIFT_LAYER] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, td_shift_layer_finished, td_shift_layer_reset),
};

// Caps Word customization
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case KC_A ... KC_Z:
            add_weak_mods(MOD_BIT(KC_LSFT)); // Apply shift to next key.
            return true;

        // Keycodes that continue Caps Word, without shifting.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case KC_SPC:
        case KC_DOT:
        case KC_EQL:
        case KC_LSFT:
        case KC_RSFT:
        case CW_TOGG:
        case KC_MINS:
            return true;

        default:
            // Handle Mod-Taps and Layer-Taps
            if (IS_QK_MOD_TAP(keycode) || IS_QK_LAYER_TAP(keycode)) {
                uint16_t base_keycode = keycode & 0xFF;
                switch (base_keycode) {
                    case KC_A ... KC_Z:
                        add_weak_mods(MOD_BIT(KC_LSFT));
                        return true;
                    case KC_1 ... KC_0:
                    case KC_BSPC:
                    case KC_DEL:
                    case KC_UNDS:
                    case KC_SPC:
                    case KC_DOT:
                    case KC_EQL:
                    case KC_MINS:
                        return true;
                }
            }
            return false; // Deactivate Caps Word
    }
}


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* Layer 0 - Base Layer
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * | ESC  |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  |  -   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | Tab  |   Q  |   W  |   E  |   R  |   T  |                    |   Y  |   U  |   I  |   O  |   P  |  =   |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |CtlEsc|   A  |   S  |   D  |   F  |   G  |-------.    ,-------|   H  |   J  |   K  |   L  |   ;  |Ctl/' |
 * |------+------+------+------+------+------| Enter |    |CapsWrd|------+------+------+------+------+------|
 * |LShift|   Z  |   X  |   C  |   V  |   B  |-------|    |-------|   N  |   M  |   ,  |   .  |   /  |SftEnt|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      | LAlt |Gui/Spc| |LT2Spc|       \SftEnt\  |LT1Spc| RGUI | RAlt |
 *                   |      |      |       |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
    [0] = LAYOUT(
        KC_ESC,          KC_1,  KC_2,  KC_3,  KC_4,  KC_5,                           KC_6,  KC_7,  KC_8,     KC_9,    KC_0,     KC_MINS,
        KC_TAB,          KC_Q,  KC_W,  KC_E,  KC_R,  KC_T,                           KC_Y,  KC_U,  KC_I,     KC_O,    KC_P,     KC_EQL,
        LCTL_T(KC_ESC),  KC_A,  KC_S,  KC_D,  KC_F,  KC_G,                           KC_H,  KC_J,  KC_K,     KC_L,    KC_SCLN,  RCTL_T(KC_QUOT),
        KC_LSFT,         KC_Z,  KC_X,  KC_C,  KC_V,  KC_B,  KC_ENT,        CW_TOGG,  KC_N,  KC_M,  KC_COMM,  KC_DOT,  KC_SLSH,  SC_SENT,
            KC_NO,  KC_LALT,  LGUI_T(KC_SPC),  LT(2,KC_SPC),                        SC_SENT,  LT(1,KC_SPC),  KC_RGUI,  KC_RALT
    ),

/* Layer 1 - Symbol/Function Layer
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |  F1  |  F2  |  F3  |  F4  |  F5  |                    |  F6  |  F7  |  F8  |  F9  | F10  | F11  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   1  |   2  |   3  |   4  |   5  |                    |   6  |   7  |   8  |   9  |   0  | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   !  |   ?  |   [  |   ]  |   '  |-------.    ,-------|  ←   |  ↓   |  ↑   |  →   | Bksp |      |
 * |------+------+------+------+------+------|       |    |CapsWrd|------+------+------+------+------+------|
 * |      |      |      |   (  |   )  |   :  |-------|    |-------|  `   |  \   |   -  |   .  |   =  |RShift|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /LShift/        \      \  |      |LAG_T |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
    [1] = LAYOUT(
        KC_TRNS,  KC_F1,    KC_F2,    KC_F3,    KC_F4,    KC_F5,                                   KC_F6,    KC_F7,    KC_F8,    KC_F9,    KC_F10,   KC_F11,
        KC_TRNS,  KC_1,     KC_2,     KC_3,     KC_4,     KC_5,                                    KC_6,     KC_7,     KC_8,     KC_9,     KC_0,     KC_F12,
        KC_TRNS,  KC_EXLM,  KC_QUES,  KC_LBRC,  KC_RBRC,  KC_QUOT,                                 KC_LEFT,  KC_DOWN,  KC_UP,    KC_RGHT,  KC_BSPC,  KC_TRNS,
        KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_LPRN,  KC_RPRN,  KC_COLN,  LSFT(KC_ENT),        KC_TRNS,  KC_BSLS,  KC_GRV,   KC_MINS,  KC_PDOT,  KC_EQL,   KC_RSFT,
                            KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_LSFT,                              KC_TRNS,  KC_TRNS,  LAG_T(KC_NO),  KC_TRNS
    ),

/* Layer 2 - Navigation/Media Layer
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |LCG Q |  F1  |  F2  |  F3  |  F4  |  F5  |                    |  F6  |  F7  |  F8  |  F9  | F10  | F11  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |SftTab|      |LSG [ |MWhlUp|LSG ] |LSG T |                    |Sft Y |Sft U |Sft I |Sft O |Sft P | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |Gui [ |MWhlL |MWhlDn|MWhlR |CtlEnt|-------.    ,-------|Sft H |Sft J |Sft K |Sft L |  :   |  "   |
 * |------+------+------+------+------+------|SftEnt |    |       |------+------+------+------+------+------|
 * |LSG 4 |      | Mute | Vol- | Vol+ |Gui M |-------|    |-------|Sft N |Sft M |  <   |  >   |  ?   |SftEnt|
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \ MO(3)\  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
    [2] = LAYOUT(
        LCG(KC_Q),     KC_F1,          KC_F2,         KC_F3,    KC_F4,         KC_F5,                                       KC_F6,       KC_F7,       KC_F8,       KC_F9,       KC_F10,      KC_F11,
        LSFT(KC_TAB),  KC_TRNS,        LSG(KC_LBRC),  MS_WHLU,  LSG(KC_RBRC),  LSG(KC_T),                                   LSFT(KC_Y),  LSFT(KC_U),  LSFT(KC_I),  LSFT(KC_O),  LSFT(KC_P),  KC_F12,
        KC_TRNS,       LGUI(KC_LBRC),  MS_WHLL,       MS_WHLD,  MS_WHLR,       LCTL(KC_ENT),                                LSFT(KC_H),  LSFT(KC_J),  LSFT(KC_K),  LSFT(KC_L),  KC_COLN,     KC_DQUO,
        LSG(KC_4),     KC_TRNS,        KC_MUTE,       KC_VOLD,  KC_VOLU,       LGUI(KC_M),   LSFT(KC_ENT),        KC_TRNS,  LSFT(KC_N),  LSFT(KC_M),  KC_LT,       KC_GT,       KC_QUES,     LSFT(KC_ENT),
                                                            KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,                         MO(3),  KC_TRNS,  KC_TRNS,  KC_TRNS
    ),

/* Layer 3 - Settings/RGB Layer
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |NKROff| NKROn|      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------.    ,-------|RGBTog|RGBMod|RGB V+|RGB V-|      |      |
 * |------+------+------+------+------+------|       |    |       |------+------+------+------+------+------|
 * |      |      |      |      |      |      |-------|    |-------|      |      |      |      |      |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \      \  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
    [3] = LAYOUT(
        KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                          NK_OFF,   NK_ON,    KC_NO,    KC_NO,    KC_NO,  KC_NO,
        KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                          KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,  KC_NO,
        KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,                          RM_TOGG,  RM_NEXT,  RM_VALU,  RM_VALD,  KC_NO,  KC_NO,
        KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO,   KC_NO,         KC_NO,  KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,  KC_NO,
                        KC_NO,  KC_NO,  KC_NO,  KC_TRNS,                   KC_TRNS,  KC_NO,  KC_NO,  KC_NO
    ),

/* Layer 4 - Shifted Layer
 * ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   Q  |   W  |   E  |   R  |   T  |                    |   Y  |   U  |   I  |   O  |   P  |      |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |   A  |   S  |   D  |   F  |   G  |-------.    ,-------|   H  |   J  |   K  |   L  |      |      |
 * |------+------+------+------+------+------|       |    | TO(0) |------+------+------+------+------+------|
 * |      |   Z  |   X  |   C  |   V  |   B  |-------|    |-------|   N  |   M  |   _  |   .  |   =  |      |
 * `-----------------------------------------/       /     \      \-----------------------------------------'
 *                   |      |      |      | /       /       \      \  |      |      |      |
 *                   |      |      |      |/       /         \      \ |      |      |      |
 *                   `----------------------------'           '------''--------------------'
 */
    [4] = LAYOUT(
        KC_TRNS,  KC_TRNS,     KC_TRNS,     KC_TRNS,     KC_TRNS,     KC_TRNS,                             KC_TRNS,     KC_TRNS,     KC_TRNS,     KC_TRNS,     KC_TRNS,     KC_TRNS,
        KC_TRNS,  LSFT(KC_Q),  LSFT(KC_W),  LSFT(KC_E),  LSFT(KC_R),  LSFT(KC_T),                          LSFT(KC_Y),  LSFT(KC_U),  LSFT(KC_I),  LSFT(KC_O),  LSFT(KC_P),  KC_TRNS,
        KC_TRNS,  LSFT(KC_A),  LSFT(KC_S),  LSFT(KC_D),  LSFT(KC_F),  LSFT(KC_G),                          LSFT(KC_H),  LSFT(KC_J),  LSFT(KC_K),  LSFT(KC_L),  KC_TRNS,     KC_TRNS,
        KC_TRNS,  LSFT(KC_Z),  LSFT(KC_X),  LSFT(KC_C),  LSFT(KC_V),  LSFT(KC_B),  KC_TRNS,        TO(0),  LSFT(KC_N),  LSFT(KC_M),  KC_UNDS,     KC_PDOT,     KC_PEQL,     KC_TRNS,
                                                KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,                  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS
    )
};
